FROM alpine:3.4 AS builder
WORKDIR /block-ddnet
COPY . .
RUN apk update && apk upgrade && apk add g++ cmake make python3 sqlite-dev
RUN cmake -DCLIENT=OFF -DCMAKE_BUILD_TYPE=Release . && make -j

FROM alpine:3.4
WORKDIR /srv
COPY --from=builder /block-ddnet/DDNet-Server .
# COPY --from=builder /block-ddnet/autoexec.cfg .
COPY --from=builder /block-ddnet/data/maps/ maps
COPY --from=builder /usr/lib/libgcc_s.so.1 /usr/lib/libstdc++.so.6 /usr/lib/libsqlite3.so.0 /usr/lib/
CMD ["./DDNet-Server"]
